name: github pages deployment
on: workflow_dispatch
  
permissions:
  id-token: write
  pages: write
  contents: read 
  
jobs:
  github-pages:
    name: github pages
    uses: anantacloud/workflows/.github/workflows/github-pages-deployment.yaml@main
    with:
      runner_label: "cloud-runner"
    secrets: inherit
