name: github pages deployment
on:
  push:
    branches:
      - gh-pages
jobs:
  github-pages:
    name: github pages
    uses: anantacloud/workflows/.github/workflows/github-pages-deployment.yaml@main
    with:
      runner_label: "cloud-runner"
      checkout_dir: "/apps/anantacloud/runner/${{ github.repository }}"
    secrets: inherit

